name: Upload Website

on:
   push:
      branches:
         - main

jobs:
   deploy:
      runs-on: ubuntu-latest
      environment: main
      steps:
         - name: Checkout
           uses: actions/checkout@v1

         - name: Configure AWS Credentials
           uses: aws-actions/configure-aws-credentials@v1
           with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: us-east-1

         - name: Configurar permissões públicas do S3
           run: |
              aws s3api put-bucket-acl --bucket seu-bucket --acl public-read
              aws s3api put-bucket-policy --bucket seu-bucket --policy '{
              "Version": "2012-10-17",
              "Statement": [
              {
               "Effect": "Allow",
               Principal": "*",
               "Action": ["s3:GetObject"],
               "Resource": ["arn:aws:s3:::embarcacao-app/*"]
              }
              ]
              }'
         - name: Deploy static site to S3 bucket
           run: aws s3 sync ./dist/ s3://embarcacao-app
